### ISSUE TITLE
Lab requires local tests to pass, but there is not a spec directory

### ISSUE THREAD

**Issue by marycodes2** [learn-co-curriculum/hs-zhw-shoes-layout#11]

**Comment by d-d-d-dalia** [comment]
I had a student with the same issue today.

**Comment by d-d-d-dalia** [comment]
Another student today.

**Comment by ivalentine** [comment]
Had a student with this issue today as well.

**Comment by Sdcrouse** [comment]
I think this issue has been fixed. There was a spec directory when I opened this lab.

**Comment by lizbur10** [comment]
Closing - already fixed
