### ISSUE TITLE
The Clear and Float concepts have not been introduced at this point

### ISSUE THREAD

**Issue by tothutra** [learn-co-curriculum/hs-zhw-shoes-layout#3]
I googled a lot to complete this lab and and found out that the all the important element to solved this were introduced in the following lessons. 

I think this lab should me moved to the next section. 

Thanks! 

Tra

**Comment by AnnJohn** [comment]
Hi @tttra thanks for raising this issue. We'll look into it!

**Comment by jongrover** [comment]
@tttra you are correct these were supposed to be placed in the next unit on CSS Layout. @AnnJohn is moving these to the correct location for future students. Thanks.
