### ISSUE TITLE
Run local test error

### ISSUE THREAD

**Issue by toanhtran** [learn-co-curriculum/hs-zhw-shoes-layout#7]
Here are the steps for this lab: Steps

Fork this repository
Clone Your fork
cd into the folder for your cloned copy of this lab.
Write necessary CSS in layout.css file to create column structure to match the MOCKUP.jpg file.
Please install Firefox if you haven't already as it is required for the screenshot tests to run.
## When your done, type learn command from Terminal to run local tests.

When I typed learn in my Terminal I got an error message because there are no rspec test. learn
This directory doesn't appear to have any specs in it. 
<img width="279" alt="screen shot 2016-03-17 at 6 25 16 pm" src="https://cloud.githubusercontent.com/assets/10580157/13841996/4e93deec-ec6f-11e5-9a53-47270daf7228.png">

**Comment by AnnJohn** [comment]
hi @toanhtran there are some issues with the specs with our HTML/CSS labs which we're working on fixing, and they should be resolved by the end of the day. Sorry for the issue!
